name: tests

on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: npm install
        run: npm i
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        with:
          command: npm run e2e
          start: npm run start:test
          wait-on: http://localhost:8000
